# Generated by Django 5.1.2 on 2024-10-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='products',
        ),
    ]
