# Generated by Django 5.1.2 on 2024-10-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_product_wishlist_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='added_date',
            new_name='created_at',
        ),
    ]
